### ISSUE TITLE
Application not working "https://angular.microfrontends.app/"

### ISSUE THREAD

**Issue by apmeena** [angular-microfrontends/root-config#1]
Hi, 
I am getting the below error when I am trying to run https://angular.microfrontends.app/
please refer to the below image for the error description.

![error](https://user-images.githubusercontent.com/6169344/82307285-c4fda200-99dd-11ea-97b1-76fe918ba512.PNG)

**Comment by joeldenning** [comment]
This example is not yet functional, which is why it is not linked to anywhere. I've shifted focus to some other projects right now (single-spa-layout) and will hopefully come back to this later. If you have interest in collaborating on this example to get it up and going sooner, I'd be happy to review any PRs and help you get started on it.
